#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
use lib ( $FindBin::Bin );  # for local modules
use CwcConfig;

use Getopt::Long;
use Path::Class;

# ------------------------------------------------------------
# Constant values

# Base location of cwc-integ stuff.
my $base_dir = dir($FindBin::Bin, "..")->resolve();

# This is the config file we'll write.
my $cwc_source_config_filename = file($base_dir, "cwc-source-config.lisp")->absolute();

# ------------------------------------------------------------
# Global Variables

# Set to enable verbose (debugging) output.
my $verbose = 0;

# ------------------------------------------------------------
# Parse Arguments

GetOptions('v|verbose'          => \$verbose,
          )
  or die("Error parsing arguments.");

# ------------------------------------------------------------
# Perform any one-time setup.

# By default, do everything from the cwc-integ root dir.
chdir($base_dir);
$verbose and
  print("Running in: " . dir(".")->absolute . "\n");

CwcConfig::load_config(1);

# ------------------------------------------------------------
# FIXME Make a config!

print("Writing config file: $cwc_source_config_filename\n");
open(my $fh, ">", $cwc_source_config_filename) or
  die("Unable to open file for writing: $cwc_source_config_filename");

# First, write a warning header.
print($fh ";; AUTO-GENERATED FILE\n");
my $script_filename = file(__FILE__)->absolute();
print($fh ";; This file was generated by: $script_filename\n");
print($fh "\n");



exit(0);

# End of main script
# ------------------------------------------------------------
# Subroutines
